name = "stacktrace"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "stacktrace"
database_id = "70239306-1583-4029-9de8-5a32cda545be"

[[kv_namespaces]]
binding = "KV"
id = "3e67b719630c4cf68b727547b60a9ab9"
